### ISSUE TITLE
🔨 Pass static analysis

### ISSUE THREAD

**Issue by Shadow60539** [AbhishekDoshi26/parent-child-checkbox#2]
Execute `dart format lib/parent_child_checkbox.dart`

to score 130 in [pub](https://pub.dev/packages/parent_child_checkbox/score)

**Comment by AbhishekDoshi26** [comment]
@Shadow60539 I do have the idea of this. I will be doing this along with new features in the next version. It's not a wise step to just release a new version for formatting.
